/** @type {import('tailwindcss').Config} */

// Every colour resolves to a CSS variable defined in src/index.css, so the
// light/dark palettes swap by toggling the `dark` class on <html>.
const token = name => `rgb(var(--${name}) / <alpha-value>)`

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'error-container': token('error-container'),
        'on-secondary': token('on-secondary'),
        'inverse-on-surface': token('inverse-on-surface'),
        'background': token('background'),
        'on-primary-container': token('on-primary-container'),
        'on-tertiary-fixed': token('on-tertiary-fixed'),
        'on-primary-fixed-variant': token('on-primary-fixed-variant'),
        'on-primary-fixed': token('on-primary-fixed'),
        'inverse-surface': token('inverse-surface'),
        'on-secondary-fixed': token('on-secondary-fixed'),
        'on-error': token('on-error'),
        'tertiary-fixed': token('tertiary-fixed'),
        'error': token('error'),
        'tertiary': token('tertiary'),
        'on-tertiary-fixed-variant': token('on-tertiary-fixed-variant'),
        'secondary': token('secondary'),
        'primary-fixed': token('primary-fixed'),
        'surface-container': token('surface-container'),
        'primary-fixed-dim': token('primary-fixed-dim'),
        'surface-dim': token('surface-dim'),
        'tertiary-container': token('tertiary-container'),
        'surface-container-lowest': token('surface-container-lowest'),
        'on-secondary-container': token('on-secondary-container'),
        'surface-container-highest': token('surface-container-highest'),
        'outline': token('outline'),
        'surface': token('surface'),
        'on-secondary-fixed-variant': token('on-secondary-fixed-variant'),
        'on-primary': token('on-primary'),
        'surface-tint': token('surface-tint'),
        'surface-container-high': token('surface-container-high'),
        'surface-bright': token('surface-bright'),
        'surface-variant': token('surface-variant'),
        'secondary-container': token('secondary-container'),
        'on-tertiary': token('on-tertiary'),
        'surface-container-low': token('surface-container-low'),
        'on-tertiary-container': token('on-tertiary-container'),
        'primary': token('primary'),
        'outline-variant': token('outline-variant'),
        'inverse-primary': token('inverse-primary'),
        'secondary-fixed': token('secondary-fixed'),
        'on-surface': token('on-surface'),
        'primary-container': token('primary-container'),
        'secondary-fixed-dim': token('secondary-fixed-dim'),
        'tertiary-fixed-dim': token('tertiary-fixed-dim'),
        'on-background': token('on-background'),
        'on-surface-variant': token('on-surface-variant'),
        'on-error-container': token('on-error-container'),
        'scrim': token('scrim'),
      },
      borderRadius: {
        DEFAULT: '4px',
        sm: '2px',
        md: '6px',
        lg: '8px',
        xl: '12px',
        '2xl': '16px',
        '3xl': '24px',
        full: '9999px',
      },
      spacing: {
        'base': '8px',
        'panel-sidebar': '320px',
        'panel-cart': '400px',
        'gutter': '16px',
        'margin-desktop': '24px',
        'margin-mobile': '16px',
        'touch-target-min': '48px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '26px', fontWeight: '400' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'display-price': ['48px', { lineHeight: '56px', fontWeight: '700', letterSpacing: '-0.02em' }],
      },
      boxShadow: {
        'card': 'var(--shadow-card)',
        'modal': 'var(--shadow-modal)',
      },
    },
  },
  plugins: [],
}
