/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#ecf1ff',
        'background': '#f9f9ff',
        'on-primary-container': '#fefcff',
        'on-tertiary-fixed': '#311400',
        'on-primary-fixed-variant': '#004395',
        'on-primary-fixed': '#001a42',
        'inverse-surface': '#263143',
        'on-secondary-fixed': '#002113',
        'on-error': '#ffffff',
        'tertiary-fixed': '#ffdcc6',
        'error': '#ba1a1a',
        'tertiary': '#924700',
        'on-tertiary-fixed-variant': '#723600',
        'secondary': '#006c49',
        'primary-fixed': '#d8e2ff',
        'surface-container': '#e7eeff',
        'primary-fixed-dim': '#adc6ff',
        'surface-dim': '#cfdaf2',
        'tertiary-container': '#b75b00',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#00714d',
        'surface-container-highest': '#d8e3fb',
        'outline': '#727785',
        'surface': '#f9f9ff',
        'on-secondary-fixed-variant': '#005236',
        'on-primary': '#ffffff',
        'surface-tint': '#005ac2',
        'surface-container-high': '#dee8ff',
        'surface-bright': '#f9f9ff',
        'surface-variant': '#d8e3fb',
        'secondary-container': '#6cf8bb',
        'on-tertiary': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'on-tertiary-container': '#fffbff',
        'primary': '#0058be',
        'outline-variant': '#c2c6d6',
        'inverse-primary': '#adc6ff',
        'secondary-fixed': '#6ffbbe',
        'on-surface': '#111c2d',
        'primary-container': '#2170e4',
        'secondary-fixed-dim': '#4edea3',
        'tertiary-fixed-dim': '#ffb786',
        'on-background': '#111c2d',
        'on-surface-variant': '#424754',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '4px',
        sm: '2px',
        md: '6px',
        lg: '8px',
        xl: '12px',
        '2xl': '16px',
        '3xl': '24px',
        full: '9999px',
      },
      spacing: {
        'base': '8px',
        'panel-sidebar': '320px',
        'panel-cart': '400px',
        'gutter': '16px',
        'margin-desktop': '24px',
        'margin-mobile': '16px',
        'touch-target-min': '48px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '26px', fontWeight: '400' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'display-price': ['48px', { lineHeight: '56px', fontWeight: '700', letterSpacing: '-0.02em' }],
      },
      boxShadow: {
        'card': '0px 4px 12px rgba(30, 41, 59, 0.08)',
        'modal': '0px 8px 32px rgba(30, 41, 59, 0.16)',
      },
    },
  },
  plugins: [],
}
